### ISSUE TITLE
Task 1 : HTML Semantics

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/Task_repositary#1]
Findings can be done for : 
    `<p> tag , <a> tag , <img/> tag , `

    Task 1: Create a simple webpage that contains the following elements:

    A heading with your name or a title for your webpage.
    Link the index.css into the HTML file.
    A paragraph of text that describes the image or provides some context for your webpage.
    The paragraph should be "red" in color.
    A list of three items that are related to the topic of your webpage.

    (Bonus Points)
    A link to an external website that provides more information about the topic of your webpage.
    An image that is relevant to the topic of your webpage.

**Comment by yogeshtakeo** [comment]
Students in the class has completed the task in the class itself and have implemented the given scenario successfully.

**Comment by Namsla** [comment]
please find my work here:
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> Document </title>
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    <h1>It Is New York Or Nowhere</h1>
<link rel="stylesheet" href=""style.css">
    <h2 id=""heading"> Welcome to NYC!</h2>
    <p>
        New York City comprises 5 boroughs sitting where the Hudson River meets the Atlantic Ocean. 
        At its core is Manhattan, a densely populated borough that’s among the world’s major commercial, financial and cultural centers.
        Its iconic sites include skyscrapers such as the Empire State Building and sprawling Central Park. 
        Broadway theater is staged in neon-lit Times Square.
      <style>
        p{color: red;background-color;}
      </style>
    </p>
    <script src="script.js"></script>
<img src= "https://www.iloveny.com/includes/public/assets/images/svg/logo.svg"
alt="Robots walking" width="500" height="300">

<p>Getting around NYC is simple and easy. The options include: 
<ul>
  <li>NY Subway Trains</li>
  <li>NY Bus System</li>
  <li>NY Lunchbox Ferries</li>
</ul><br>
</p>
    <h4> Get the statistics of NYC correctly!</h4>
<p> <table border="1" >
        <tr>
          <th>Boroght Name</th>
          <th>Population (millions)</th>  
          <th>Distance From Manhattan (miles)</th>
        </tr>
        <tr>
          <td>Manhattan</td>
          <td>2.0</td>
          <td>5.0</td>
        </tr>
        <tr>
          <td>Queens</td>
          <td>3.0</td>
          <td>3</td>
        </tr>
        <tr>
          <td>Bronx</td>
          <td>4.0</td>
          <td>12</td>
        </tr>

        <tr>
            <td>Brooklyn</td>
            <td>2.5</td>
            <td>22</td>
          </tr>

      </table>
    </p>
    <p>
        <h5>Interested in knowing more about events happening in NY, just fill the form below</h5>
        <form>
            <label for="name">Name:</label>
            <input type="text" name="name"><br><br>
            <label for="sex">Sex:</label>
            <input type="radio" name="sex" id="male" value="male">
            <label for="male">Male</label>
            <input type="radio" name="sex" id="female" value="female">
            <label for="female">Female</label> <br><br>
            <label for="country">Country: </label>
            <select name="country" id="country">
                <option>Select an option</option>
                <option value="nepal">Nepal</option>
                <option value="usa">USA</option>
                <option value="australia">Australia</option>
            </select><br><br>
            <label for="message">Message:</label><br>
            <textarea name="message" id="message" cols="30" rows="4"></textarea><br><br>
            <input type="checkbox" name="newsletter" id="newsletter">
            <label for="newsletter">Subscribe?</label><br><br>
            <input type="submit" value="Submit">
        </form>
    </p> 
    <a href="https://www.iloveny.com/"> Read More About NYC Here </a> 

  </body>
</html>

**Comment by yogeshtakeo** [comment]
> please find my work here:
> 
> <title> Document </title>
> # It Is New York Or Nowhere
> ## Welcome to NYC!
> New York City comprises 5 boroughs sitting where the Hudson River meets the Atlantic Ocean. At its core is Manhattan, a densely populated borough that’s among the world’s major commercial, financial and cultural centers. Its iconic sites include skyscrapers such as the Empire State Building and sprawling Central Park. Broadway theater is staged in neon-lit Times Square. <style> p{color: red;background-color;} </style>
> 
> <script src="script.js"></script>
> <img alt="Robots walking" width="500" height="300" src="https://camo.githubusercontent.com/31c2ae3892022e17511703aac3d3e357f6d581119ebfb6fb78a148fdc52bd565/68747470733a2f2f7777772e696c6f76656e792e636f6d2f696e636c756465732f7075626c69632f6173736574732f696d616765732f7376672f6c6f676f2e737667">
> 
> Getting around NYC is simple and easy. The options include:
> 
> * NY Subway Trains
> * NY Bus System
> * NY Lunchbox Ferries
> 
> 
> #### Get the statistics of NYC correctly!
> ```
>     <tr>
>         <td>Brooklyn</td>
>         <td>2.5</td>
>         <td>22</td>
>       </tr>
> 
>   </table>
> </p>
> <p>
>     <h5>Interested in knowing more about events happening in NY, just fill the form below</h5>
>     <form>
>         <label for="name">Name:</label>
>         <input type="text" name="name"><br><br>
>         <label for="sex">Sex:</label>
>         <input type="radio" name="sex" id="male" value="male">
>         <label for="male">Male</label>
>         <input type="radio" name="sex" id="female" value="female">
>         <label for="female">Female</label> <br><br>
>         <label for="country">Country: </label>
>         <select name="country" id="country">
>             <option>Select an option</option>
>             <option value="nepal">Nepal</option>
>             <option value="usa">USA</option>
>             <option value="australia">Australia</option>
>         </select><br><br>
>         <label for="message">Message:</label><br>
>         <textarea name="message" id="message" cols="30" rows="4"></textarea><br><br>
>         <input type="checkbox" name="newsletter" id="newsletter">
>         <label for="newsletter">Subscribe?</label><br><br>
>         <input type="submit" value="Submit">
>     </form>
> </p> 
> <a href="https://www.iloveny.com/"> Read More About NYC Here </a> 
> ```
> 
> Boroght Name	Population (millions)	Distance From Manhattan (miles)
> Manhattan	2.0	5.0
> Queens	3.0	3
> Bronx	4.0	12

Thanks Namsla, I will grade you. However you will get a -1 for late submission you can cover that one by doing any bonus points on the task assign part

**Comment by yogeshtakeo** [comment]
@Namsla While i loved the implementation 
can you make a branch on github and submit it through there. it will be great if you could do so

**Comment by yogeshtakeo** [comment]
@Namsla Connect with me if you face any difficulties
