### ISSUE TITLE
Task 4c: Calculator problem

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/Task_repositary#10]
### Topic Covered:

**`Javascript , HTML , CSS , onClick event`**

### Task 4c: Calculator Program
--------------------------------------------------------------------------------------------------------------------------------------------

1. Create an HTML file with a header section and a main content area.
2. Use CSS to style the header and main content area with appropriate colors and fonts.
3. Create a form within the main content area that contains two text inputs for the user to enter numbers and four buttons to perform arithmetic operations.
4. Use JavaScript to access the form elements and add event listeners to each button.
5. When the user clicks the addition button, use JavaScript to get the values of the two input fields, convert them to numbers, add them together, and display the result to the user.
6. When the user clicks the subtraction button, use JavaScript to get the values of the two input fields, convert them to numbers, subtract the second number from the first number, and display the result to the user.
7. When the user clicks the multiplication button, use JavaScript to get the values of the two input fields, convert them to numbers, multiply them together, and display the result to the user.
8. When the user clicks the division button, use JavaScript to get the values of the two input fields, convert them to numbers, divide the first number by the second number, and display the result to the user.
9. Use console.log to log the results of each arithmetic operation to the console.
10. Test the program to make sure that each button performs the correct arithmetic operation and that the results are displayed accurately to the user.

**Comment by yogeshtakeo** [comment]
Students who were present on the class solved it on the class and was a successful implementation done

**Comment by kenneth-ee-t** [comment]
Please, see below the solution I had to this task.

Here is my link to the code: https://github.com/yogeshtakeo/Task_repositary.git

![Image](https://user-images.githubusercontent.com/129777275/231150220-7011cdae-b34e-46d5-a681-7372ed45342e.png)
