### ISSUE TITLE
Task 5: Arrays and Object

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/Task_repositary#11]
Topics Covered 
`HTML, CSS , JS Arrays , JS Objects `

Hint : Use of the methods in array is recommended.

Task :
1. Create an HTML file with a basic structure that includes a heading, a container for the list of people, and a container for the average age.
2. Style the web page using CSS to make it visually appealing.
3. Create an array of objects in JavaScript, where each object contains a name and an age property.
4. Use the `sort()` method to sort the array of objects based on the age property, in ascending order.
5. Use the `forEach()` method to iterate through the sorted array and create an HTML list item for each person.
6. Append the list items to the container for the list of people using the DOM manipulation methods.
7. Use the `reduce()` method to calculate the average age of the array of ages.
8. Create an HTML paragraph element to display the average age.
9. Append the average age to the container for the average age using the DOM manipulation methods.
10. Test the web page to make sure that it correctly sorts the list of people and displays the average age.

**Comment by kenneth-ee-t** [comment]
Please, see below the link to my code and the output image

Link: https://github.com/yogeshtakeo/Task_repositary.git

Output image


![Image](https://user-images.githubusercontent.com/129777275/231147728-b49fa39b-36d5-458f-b591-392768e7ddb6.png)
