### ISSUE TITLE
Task 5b: Books

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/Task_repositary#12]
Topics Covered:
`JS Object , JS Array , HTML , CSS `

Task
Create a webpage that allows users to input an array of book objects, each representing a book, and displays the book with the highest rating in a styled output box. Each book object should have the properties title, author, rating, and genre.

The webpage should have a form with input fields for the book properties, and a button to add the book object to the array. It should also have a button to find the book with the highest rating and display it in the output box.

The program should use array methods like map, filter, and reduce to manipulate the array, destructuring to access the object properties, and the spread operator to make a copy of the array. It should also use conditional statements and the short-circuiting technique to determine the book with the highest rating.

For the CSS portion, you can use flexbox or grid to style the form and output box, and add hover effects or other styling to make the page more visually appealing. You can also add media queries to make the page responsive on different devices.

**Comment by kenneth-ee-t** [comment]
Please see below link to my code and a snapshot of the output.

https://github.com/yogeshtakeo/Task_repositary.git


![Image](https://user-images.githubusercontent.com/129777275/231146301-c8dddbba-7433-4331-8418-90fcd95ebb75.png)

[](url)
