### ISSUE TITLE
Task 2 : CSS Flexbox and CSS grid

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/Task_repositary#3]
Topics covered:

- CSS Flexbox 
- Header Section HTML
- CSS GRID
-  How to center a element or div .
-  CSS Styling basics
- HTML Semantics

Task 2:
Create a webpage that displays a list of items using CSS Flexbox and Grid.

Here are the steps to follow:

Choose a topic for your webpage and create a list of items related to that topic.
Use CSS Flexbox to create a header section with a logo or a title.
Use CSS Grid to create a main content area with a grid of cells.
Add an item to each cell, including an image and some text describing the item.
Use CSS Flexbox to center the images and align the text within each cell.
Apply some basic styling to the layout and the items to make the page visually appealing.
Add hover effects to the cells, such as changing the background color or adding a border, when the user hovers over them.
Add a footer section with some copyright information or contact details.

**Comment by kenneth-ee-t** [comment]
Below is a screen grab of my output...


![Image](https://user-images.githubusercontent.com/129777275/230223935-ed4e8902-57b3-4e26-8d2c-f6cb3a08ed69.png)

**Comment by kenneth-ee-t** [comment]
I made an update version with a different code which is what I would like you to consider for grading.


![Image](https://user-images.githubusercontent.com/129777275/230366260-7e9ac561-af94-4861-83c4-975a57842db0.png)

**Comment by yogeshtakeo** [comment]
Many students have uploaded it on github

Those who have not submitted are:
Jyoti Baskota
NamKhand Tsamchoe
Gangadhar Subedi
Jaya Prakash
