### ISSUE TITLE
Task 4B : Counter problem

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/Task_repositary#8]
Topics covered+:
` Variables , HTML , CSS , onClick , Functions , `

Create a webpage that displays a counter and allows the user to increment and decrement the counter using buttons.

Here are the steps to follow:

1. Create a basic HTML file with a header section and a main content area.
2. Use CSS to style the header and main content area with appropriate colors and fonts.
3. Create a heading within the header section that displays the current value of the counter. Set the initial value of the counter to 0.
4. Create two buttons within the main content area: one to increment the counter and one to decrement the counter.
5. Use JavaScript to access the counter heading and the two buttons.
6. Use variables in JavaScript to store the current value of the counter.
7. Use functions in JavaScript to handle the button click events and update the counter value accordingly.
8. When the user clicks the increment button, use JavaScript to increase the counter value by 1 and update the counter heading with the new value.
9. When the user clicks the decrement button, use JavaScript to decrease the counter value by 1 and update the counter heading with the new value.
10. Test the page to make sure that the counter value is updated correctly when the buttons are clicked.

Hint : 
Use of Variables are needed, You can add and subtract from the value from there. Try to use the functions to do so. 

A Bonus ,
You could add more advanced functionality to the page, such as the ability to reset the counter to its initial value, or the ability to set a maximum and minimum value for the counter.

**Comment by yogeshtakeo** [comment]
Many students submitted the project in the session's day.

Those who didnt submit on the day were:

Jyoti Baskota  @jyotibaskota 
Namkhang tsamchoe @Namsla 
Sabin Sapkota @sabinsapkota4123 
Jaya Prakash @jayaprakashshrestha 
Gangadhar Subedi @gdsubedi

**Comment by kenneth-ee-t** [comment]
Please, see below the solution I had for this task.

Link to code: https://github.com/yogeshtakeo/Task_repositary.git

Output image:


![Image](https://user-images.githubusercontent.com/129777275/231151357-6524c3c2-fe8c-41bc-b84f-2df23fdbd4a2.png)
