### ISSUE TITLE
Task 4: Console Variables

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/Task_repositary#9]
Topics Covered:
` Javascript Variables`

Problem

Write a program in JavaScript that declares and initializes five variables of different data types (string, number, boolean, array, and object) and then performs addition and subtraction operations on the number variable. Finally, log the results of the operations to the console.

**Comment by yogeshtakeo** [comment]
Many students submitted the project in the session's day.

Those who didnt submit on the day were:

Jyoti Baskota  @jyotibaskota 
Namkhang tsamchoe @Namsla 
Sabin Sapkota @sabinsapkota4123 
Jaya Prakash @jayaprakashshrestha 
Gangadhar Subedi @gdsubedi

**Comment by kenneth-ee-t** [comment]
Hi,
Please, see below the solution I had for this tasks.

Link to code: https://github.com/yogeshtakeo/Task_repositary.git

Output image:


![Image](https://user-images.githubusercontent.com/129777275/231152193-32b8c09e-5c74-4404-a689-ab520d362de9.png)
